name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      path: cloud-resume-sam-template 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 botocore pytest
        pip install -e .

    - name: Run tests
      working-directory: cloud-resume-sam-template
      run: |
        pytest tests/unit/test_lambda_functions.py
