name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Change directory
      run: cd cloud-resume-sam-template

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 botocore pytest
        pip install -e .

    - name: Run tests
      run: |
        cd ..  # Navigate back to the main repository directory
        pytest cloud-resume-sam-template/tests/unit/test_lambda_functions.py
